### ISSUE TITLE
Add Gear Set Length Causes tabs to shift right

### ISSUE THREAD

**Issue by Shadowtrance** [BDO-Planner/issues#244]
**Describe the bug**
Add Gear Set text length causes tabs to shift right depending on the language of varying degrees. And in some/most cases causes the **+** button to be eaten alive in the process.

**To Reproduce**
1. Go to character build page.
2. Change language to...
Japanese (tiny shift)
German (small shift oddly enough, button still eaten)
Spanish (big shift, button eaten)
French (small shift, button eaten)
Russian (big shift, button eaten, new translation fixes it just barely)
Portuguese (big shift, button eaten)
3. Watch the tabs move. :)

**Expected behavior**
They shouldn't move I guess? lol

**Additional context**
Translations just need to be better in some part like this, shortened / abbreviated.
So maybe the app itself doesn't need changing to suit, I don't know.

**Comment by Ihellmasker** [comment]
Yeah potentially we need to fix the translations on these really. I could probably hack some CSS like this, ignore the icon alignment: 
![Uploading image.png…]()
but the text is just getting clipped anyway, so there's no benefit to it being there really.

**Comment by Ihellmasker** [comment]
Change of plan, moved the label into a tooltip instead.

![image](https://user-images.githubusercontent.com/3030516/126474992-085d9e3e-d19a-4159-b451-4e38fa74d6c2.png)
