### ISSUE TITLE
BDO Planner Mobile App

### ISSUE THREAD

**Issue by Outlawz19** [BDO-Planner/issues#246]
Hello developers, I have been using this website for a long time and it's nice to have this because you'll know what to build for your class. I have problems on loading the website in mobile. It's too slow and it's a bit mess when using mobile. I hope you can make an app for this for a better experience. Thanks

**Comment by Ihellmasker** [comment]
Unfortunately, we have no intention of making an app at this time. We have neither the time, understanding or money to make one.

I am currently working on improving the loading experience as it is admittedly quite bad now but the change to load times had to be done to stop the server crashing.

As for it being a mess when using mobile, can you be more specific? Improvements have been made to the site in mobile view and I'm not aware of any issues with it.

**Comment by Shadowtrance** [comment]
NO! Making an app (if even possible... not saying it is or isn't) won't make it magically load any damn faster! JFC!

It still has to load data (and save) from / to the database....

You already have an app, it's called "your web browser of choice".... the only "issues" with mobile view is really only when your screen resolution is below 1080p.... then things get a bit strange, if it is below 1080p, time to upgrade. :P

But please do elaborate on this "mess when using mobile" part. We aren't mind readers....

An app isn't the magical solution to everything that people seem to think it is, but we are open to suggestions for improvements, especially on the mobile side of things as we know it isn't perfect (nothing ever is).
