### ISSUE TITLE
Gear price

### ISSUE THREAD

**Issue by exi66** [BDO-Planner/issues#256]
add support for prices from the game market for calculating the price of the gear. This will be useful for calculating the next steps or for creating an optimal build from scratch.

**Comment by Ihellmasker** [comment]
Unfortunately, we have no official way to get this information.

I know people have made some sheets/tools that use the API from the app to grab data, but that isn't exactly allowed, and we don't want to start doing things like that and piss PA off, as they could very easily just shut us down and we couldn't do anything about it.

Until an official developer API is opened for this, we will not be adding this.
