### ISSUE TITLE
Corsair character planner does not show correct level stats

### ISSUE THREAD

**Issue by sl-einert** [BDO-Planner/issues#264]
**Describe the bug**
If a Corsair is selected in the character planer and leveled up the HP, MP and Weight Limit is not increased correctly.

**To Reproduce**
1. Go to 'https://bdoplanner.com/classes'
2. Click on 'Corsair'
3. Click on 'Character' tab
4. Change value of 'Basic' 'Level' to 60
5. See that 'Max HP', 'Max MP/WP/SP' and 'Weight Limit' are still on an unrealistic low level.

**Expected behavior**
Values should reflect the real values.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/59532465/133983142-ce98210f-ac1a-4baa-a8fe-0ba7aed40f7b.png)
![grafik](https://user-images.githubusercontent.com/59532465/133983227-d978baaf-c1e0-49b3-a412-5fe8ad3d469f.png)

**Comment by Shadowtrance** [comment]
Base stats for all classes after **shai** are not fully known (from level 1 - 99 like the rest) and therefore incomplete in planner until such time all the data is available.

**Comment by Ihellmasker** [comment]
For further context before I close it, in case anyone else reads it.

The stat data for all classes is not readily available to us from the game files, its protected in whatever way so we can't view it
In Sept 2019 they "leaked" and were not secured properly so we (any many others) were able to extract all the data. At the time Shai was the latest class, so we have all levelling data up to that point in Planner.

However, we have no real way to get this data for classes released after Shai, short of levelling from 1-XX on all classes ourselves and recording it, something we're not willing to do by any stretch of the imagination.

As such classes black such as Corsair, Nova, etc, will not have levelling stats, except for level 50 values for a few stats that are the same across the board, until we get those values.

Hope that explains the situation fully for anyone reading this.

**Comment by sl-einert** [comment]
Thanks for the quick and detailed response. The explanation makes sense to me 👍
