### ISSUE TITLE
Happy Black Spirit permanent buff needed

### ISSUE THREAD

**Issue by SachSage** [BDO-Planner/issues#266]
Hi
In BDO live server there's a Happy Black Spirit permanent buff which seems not to be applied in the gear planner.

Could you please add? Below is the detail of the buff
AP+1
DP+1
HP+30
MP/SP/WP +10
Stamina +20
Accuracy +4
Evasion +4
Weight +20LT

Thank you

**Comment by Shadowtrance** [comment]
It's already there. It was added shortly after it was added to the game.
It is baked into character level 1 of every class.
