### ISSUE TITLE
Lifeskill mastery from level is broken.

### ISSUE THREAD

**Issue by Hiperinio** [BDO-Planner/issues#280]
### Prerequisites

- [X] I have [searched](https://github.com/BDO-Planner/issues/issues) for duplicate or closed issues.
- [X] I have read the [Common Issues](https://github.com/BDO-Planner/issues/blob/master/README.md).

### Describe the bug

The lifeskill mastery from proffesion is broken.
It shows wrong mastery for hunting & gathering afaik.
Hunting Master 18 in game - 490 mastery / In bdoplanner - 340

### How did the bug happen

1. Go to create character
2. Go to character
3. Put your lifeskill proffesion and compare the numbers with the on in game.

### Expected behavior

To show the correct numbers.

**Comment by Ihellmasker** [comment]
There was an update in BDO a few weeks back that changed the life skill stat bonuses and I haven't had a chance to update it yet in Planner for various reasons. I will try to look at this soon :)

**Comment by Ihellmasker** [comment]
It's taken forever, but I've finally done it... Really sorry it's taken so long...
